### ISSUE TITLE
Add explicit errors

### ISSUE THREAD

**Issue by nirekin** [ekara-platform/engine#15]
The component manager returns the errors coming from external packages as is and provide no information about the origin of the error which can be useful to the end user to fix it.

**Example :** 

Using a missing component like the one is this example

```yaml
lagoon:
  components:
    aws:
      repository: tbouvet/aws-provider
```

Will break the creation process and return the following error: 

> [Error parsing the environment: reference not found]

The error gives no information about what is not found/missing/broken

We must wrap all error coming from n-tier packages and add some stuff to describe the context in order to allow the end user to fix it.
