### ISSUE TITLE
Support custom playbook path for stack deploy

### ISSUE THREAD

**Issue by adrienlauer** [ekara-platform/engine#41]
A stack deployment playbook should be customizable like this

```yaml
stacks:
  myStack:
    component: my-stack
    playbook: install.yml
```
