### ISSUE TITLE
Support file copies

### ISSUE THREAD

**Issue by adrienlauer** [ekara-platform/engine#44]
A stack component should support copying arbitrary files:

```yaml
stacks:
  myStack:
    component: _
    copies:  
    - target: 
        labels:
          label1: t1_val1   
          label2: t1_val2   
        path: "some/target1/volume/path"
      once: true
      sources:
        - "*target1_to_be_copied.yaml"
        - "*target1_to_be_copied.yml"
    - target: 
        labels:
          label1: t2_val1   
          label2: t2_val2   
        path: "some/target2/volume/path"
      sources:
        - "*target2_to_be_copied.yaml"
        - "*target2_to_be_copied.yml"
```
